easy_rec/python/compat/estimator_train.py
easy_rec/python/main.py

add support for stop training by num_epoch

add support for stop by num_epoch

---

docs/source/feature/feature.rst
pai_jobs/deploy_ext.sh

Update docs v2

---

easy_rec/python/builders/hyperparams_builder.py
easy_rec/python/model/easy_rec_estimator.py
easy_rec/python/model/easy_rec_model.py
easy_rec/python/protos/eval.proto
easy_rec/python/protos/train.proto
easy_rec/python/test/train_eval_test.py
pai_jobs/deploy.sh
pai_jobs/deploy_ext.sh
pai_jobs/easy_rec_flow_ex/easy_rec_ext.xml

update odps deploy scripts

---

docs/source/eval.md
easy_rec/__init__.py
easy_rec/python/core/distribute_metrics.py
easy_rec/python/core/metrics_impl_pai.py
easy_rec/python/core/metrics_impl_tf.py
easy_rec/python/main.py
easy_rec/python/model/easy_rec_estimator.py
easy_rec/python/model/rank_model.py
easy_rec/python/utils/estimator_utils.py
pai_jobs/run.py

add distribute evaluate for all easyrec model.

add distribute evaluate

---

easy_rec/version.py
pai_jobs/deploy_ext.sh
pai_jobs/easy_rec_flow_ex/easy_rec_ext.xml

1. update default version to stable;
2. load version info when deploy;
3. add version number;

update deployment process

---

docs/source/eval.md
easy_rec/python/core/metrics_impl_pai.py
easy_rec/python/core/metrics_impl_tf.py
easy_rec/python/main.py
easy_rec/python/model/easy_rec_estimator.py
easy_rec/python/model/rank_model.py
easy_rec/python/tools/split_model_pai.py
easy_rec/python/utils/estimator_utils.py
pai_jobs/run.py

add tool for split model and fix code style

add tool for split model and fix code style

---

easy_rec/python/model/easy_rec_model.py
samples/model_config/taobao_fg.config

fix bug in partitioned variable restore.

fix bug in partitioned variable restore.

---

easy_rec/python/model/collaborative_metric_learning.py

fix bug of co_metric_learning_i2i model

fix unit test of co_metric_learning_i2i model

---

pre-commit
scripts/gen_proto.sh
scripts/init.sh

add pre-commit hooks for check ak leak

add pre-commit hooks for check ak leak

---

easy_rec/python/test/odps_run.py
pai_jobs/easy_rec_flow_ex/easy_rec_ext.lua
samples/odps_script/boundary/train_compat.sql

ensure tables are in correct order

ensure the tables are in correct order

---

docs/source/index.rst
docs/source/metrics.md
docs/source/proto.html
easy_rec/python/builders/optimizer_builder.py
easy_rec/python/model/collaborative_metric_learning.py
easy_rec/python/model/easy_rec_estimator.py
easy_rec/python/model/wide_and_deep.py
easy_rec/python/protos/optimizer.proto
easy_rec/python/protos/train.proto
easy_rec/python/test/odps_run.py
easy_rec/python/test/train_eval_test.py
easy_rec/python/utils/multi_optimizer.py
pre-commit
samples/model_config/deepfm_freeze_gradient.config
samples/model_config/taobao_fg.json
samples/model_config/wide_and_deep_two_opti.config

1. add multi optimizer support, such as ftrl optimizer for the wide part and adam_optimize for the deep part;
2. add freeze gradient support.

[feat]: multi optimizer support and freeze gradient

---

docs/source/proto.html
easy_rec/python/input/csv_input.py
easy_rec/python/protos/dataset.proto
scripts/train_ps.sh

[feat]: support csv header

---

docs/source/models/dlrm.md
docs/source/models/rank.rst
easy_rec/python/input/input.py
easy_rec/python/model/dlrm.py
easy_rec/python/protos/dlrm.proto
easy_rec/python/protos/easy_rec_model.proto
easy_rec/python/test/train_eval_test.py
samples/model_config/dlrm_on_taobao.config

[feat] add facebook dlrm model

---

docs/source/benchmark.md
docs/source/index.rst
easy_rec/python/input/hive_input.py
easy_rec/python/main.py
easy_rec/python/protos/dataset.proto
easy_rec/python/protos/easy_rec_model.proto
easy_rec/python/protos/hive_config.proto
easy_rec/python/protos/pipeline.proto
easy_rec/python/test/hive_input_test.py
samples/emr_script/mmoe/mmoe_census_income.config

1. add benchmark doc
2. hive input and test

[hive_input][benchmark]add doc and hive_input

---

easy_rec/python/compat/estimator_train.py
easy_rec/python/input/hive_input.py
easy_rec/python/test/train_eval_test.py
easy_rec/python/utils/estimator_utils.py
easy_rec/python/utils/test_utils.py

fix final exporter not working bug.

[bugfix] fix final exporter not work bug

---

easy_rec/python/input/hive_input.py
easy_rec/python/model/easy_rec_estimator.py
easy_rec/python/protos/train.proto
samples/model_config/dlrm_on_taobao.config

add support for sparse accumulator in sync train  mode.

[feat]: support for sparse accumulator type in sync mode

---

.github/workflows/ci.yml
docs/source/benchmark.md
easy_rec/python/inference/predictor.py
easy_rec/python/test/export_test.py
easy_rec/python/test/predictor_test.py
easy_rec/python/test/run.py
easy_rec/python/utils/test_utils.py
scripts/ci_test.sh
scripts/ci_test_change_files.py

[feature]: speedup ci test

---

easy_rec/python/compat/feature_column/feature_column.py

[bugfix] fix bug for share embedding

---

easy_rec/python/feature_column/feature_column.py
easy_rec/python/layers/common_layers.py

add support for shared embedding with sequence combiner

[feature] add support for shared embedding with sequence combiner

---

.readthedocs.yaml
easy_rec/python/hpo/pai_hpo.py
requirements.txt
requirements/docs.txt
requirements/extra.txt
requirements/runtime.txt
requirements/tests.txt
scripts/build_read_the_docs.sh

fix the bug that readthedoc could not be created.

[bugfix] fix read the doc bug

---

docs/source/models/multi_tower.md
easy_rec/python/compat/feature_column/feature_column_v2.py
easy_rec/python/input/input.py
easy_rec/python/model/multi_tower.py
easy_rec/version.py
samples/model_config/multi_tower_on_taobao.config

1. remove dependency of the fix position of sample weight column
2. fix bug of share embedding of id feature and sequence feature
3. add pairwise loss option to multi tower model

[feat]: modify sample weight & add pairwise loss to multi tower model

---

docs/source/eval.md
docs/source/feature/feature.rst

add document for distribute evaluate

[docs] add document for distribute evaluate

---

.git_oss_config_pub
.github/workflows/ci_py3.yml
easy_rec/python/model/multi_tower_bst.py
easy_rec/python/test/train_eval_test.py
git-lfs/git_lfs.py

[feature]: add py3 test

---

docs/source/metrics.md

[bugfix]: fix group auc calc sql bug

---

easy_rec/python/main.py

fix the bug that not specify num_steps could not work.

[bugfix]: fix the bug that not specify num_steps do not work.

---

easy_rec/python/input/odps_rtp_input.py

fix bug of wrong variable name

fix bug of wrong variable name

---

easy_rec/python/test/hpo_test.py
easy_rec/python/utils/config_util.py
samples/hpo/hpo_param_v13.json
samples/hpo/hpo_param_v14.json

fix hpo param convert bug: https://github.com/alibaba/EasyRec/issues/155

[bugfix]: fix hpo param convert bug: issues#155

---

easy_rec/python/feature_column/feature_column.py
easy_rec/python/protos/feature_config.proto
easy_rec/python/utils/fg_util.py

allow feature wise specification of using embedding variable

[feature]: allow finer control over embedding variable

---

easy_rec/python/input/odps_rtp_input_v2.py
easy_rec/python/model/easy_rec_estimator.py
easy_rec/python/model/rank_model.py
easy_rec/python/protos/pipeline.proto
easy_rec/python/test/fg_test.py
easy_rec/python/utils/convert_rtp_fg.py
easy_rec/python/utils/fg_util.py
pai_jobs/run.py
samples/model_config/fg_train.config
samples/rtp_fg/fg_test_extensions_final.config

fix load_fg_json_to_config, make it reentrant and in front of edit_config_json

[bugfix]: fix load_fg_json_to_config, make it reentrant

---

easy_rec/python/feature_column/feature_column.py
easy_rec/python/utils/config_util.py

[bugfix]: update feature_column.py

---

docker/Dockerfile
docker/sources_18.04.list
requirements/extra.txt
scripts/build_docker.sh
scripts/gen_proto.sh

add docker file for build tf1.15 py3 docker.

[feature]: add docker file

---

easy_rec/python/protos/export.proto

[bugfix]: update export.proto

---

docs/source/models/cmbf.md
docs/source/models/dbmtl.md
easy_rec/python/layers/cmbf.py
easy_rec/python/model/cmbf.py
easy_rec/python/model/dbmtl.py
easy_rec/python/protos/layer.proto
easy_rec/version.py
samples/model_config/cmbf_on_movielens_has_other_feature.config
samples/model_config/cmbf_on_movielens_only_image_feature.config
samples/model_config/cmbf_on_movielens_only_text_feature.config

add dnn layers for other features

Features/cmbf 

---

docs/source/feature/rtp_fg.md

fix the easyrec-eas-client jar and the code demo.

Eas predict client doc fix

---

.git_bin_url
easy_rec/python/test/run.py
easy_rec/python/test/train_eval_test.py
easy_rec/python/utils/test_utils.py

limit the time of a single unit test execution.

[bugfix]: limit the time of a single test execution

---

docs/source/feature/feature.rst

[bugfix]: update feature.rst

---

easy_rec/python/tools/hit_rate_ds.py

[feat] add hitrate hdfs

---

.git_bin_path
.git_bin_url
easy_rec/python/inference/predictor.py
easy_rec/python/predict.py
easy_rec/python/test/predictor_test.py

CSVPredictor support embedding input

[feat]: CSVPredictor support embedding input

---

docs/source/eval.md
docs/source/feature/feature.rst
docs/source/feature/odl_sample.md
docs/source/index.rst
docs/source/predict/input_output.md
easy_rec/python/test/predictor_test.py

add docs for ev and sample_weight

[feature]: add docs for ev and sample_weight

---

docs/source/incremental_train.md

update fine_tune_checkpoint specification

[docs] update fine_tune_checkpoint specification

---

easy_rec/python/inference/vector_retrieve.py

[bugfix] fix typo in vector retrieve

---

docs/source/train.md
easy_rec/python/test/train_eval_test.py
easy_rec/python/train_eval.py
easy_rec/python/utils/config_util.py
easy_rec/python/utils/test_utils.py

add direct cmd args for update easyrec config

[feature] add direct cmd args for update easyrec config

---

easy_rec/python/compat/sync_replicas_optimizer.py
easy_rec/python/model/easy_rec_estimator.py

fix sync train not exit bug due to uneven dataset shard caused by filter invalid samples

[bugfix] fix sync train not exit bug due to uneven dataset shard caused by filter invalid samples

---

easy_rec/python/core/sampler.py
easy_rec/python/tools/hit_rate_ds.py
easy_rec/python/utils/config_util.py

[feat] hitrate support regular input

---

README.md
examples/readme.md

Update REAMDE and examples

---

easy_rec/python/model/dssm.py

fix predict out of dssm model
add logits_out and probs_out

fix predict out of dssm model

---

easy_rec/python/model/mind.py

fix predict shape of logits and probs in MIND model

fix predict shape of logits and probs in MIND model

---

examples/data/amazon_books_data/download_and_process.sh
examples/data/amazon_books_data/readme.md
examples/data/criteo/download_and_process.sh
examples/data/criteo/readme.md
examples/data/movielens_1m/download_and_process.sh
examples/data/movielens_1m/readme.md
examples/readme.md

添加examples下数据集的下载链接，并适配不同操作系统

---

easy_rec/python/layers/fm.py

issue:   https://github.com/alibaba/EasyRec/issues/380

[bugfix]: fix fm code in layers/fm.py

---

docs/source/benchmark.md
docs/source/eval.md
docs/source/train.md

eval page: add parameter num_thresholds  in metric auc 。

[doc] modify project name to pai_online_project in benchmark page

---

easy_rec/version.py

update easyrec version to 0.7.1

update easyrec version to 0.7.1

---

docs/source/models/wide_and_deep.md
docs/source/train.md
easy_rec/python/tools/view_saved_model.py

[feature] add view_saved_model.py

---

easy_rec/python/tools/split_pdn_model_pai.py
easy_rec/version.py

add split model script for PDN model

add split model script for PDN model

---

docs/source/export.md
easy_rec/python/export.py
easy_rec/python/inference/odps_predictor.py
easy_rec/python/main.py
easy_rec/python/test/export_test.py
easy_rec/python/utils/export_big_model.py
pai_jobs/run.py

add support for export_done_file as export done signal

[feature] add support for export_done_file as export done signal

---

docs/source/predict/MaxCompute 离线预测.md

[doc] fix predict doc

---

easy_rec/python/model/match_model.py
samples/model_config/dssm_neg_sampler_need_key_feature.config
samples/model_config/dssm_neg_sampler_sequence_feature.config

fix unsupported metric error not raised bug

[bugfix] fix not support metric error not raised bug

---

docs/source/quick_start/local_tutorial.md

Add 4 public docker images:
1. easyrec:py36-tf1.15.5-0.8.5
2. easyrec:py38-tf2.12-0.8.5
3. easyrec:py36-tf1.15.5-gpu-0.8.5
4. easyrec:py38-tf2.12-gpu-0.8.5

[feat] add public docker images
